# Generated by Django 3.0.7 on 2020-07-08 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('mail', models.EmailField(blank=True, default='', max_length=50, null=True)),
                ('created', models.DateTimeField()),
                ('massage', models.CharField(blank=True, default='', max_length=500, null=True)),
            ],
        ),
    ]
