# Generated by Django 3.0.7 on 2020-07-08 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='massage',
            field=models.TextField(blank=True, default='', max_length=500, null=True),
        ),
    ]
