# Generated by Django 3.0.7 on 2020-07-09 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20200709_0838'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task',
            new_name='Order',
        ),
    ]
